---
- name: Playbook
  hosts: prod
  tasks:
    - name: Download Zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        dest: /tmp
    - name: pkdg
      become: yes
      apt: deb="/tmp/zabbix-release_5.0-1+focal_all.deb"
    - name: Run the equivalent of "apt-get update" as a separate step
      become: yes
      apt:
        update_cache: yes
    - name: Install zabbix
      become: yes
      apt:
        name:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - php7.4-pgsql
        - zabbix-apache-conf
        - zabbix-agent
