---
all:
  hosts:
    server-01:
      ansible_host: 178.154.225.255
    server-02:
      ansible_host: 178.154.255.6
prod:
  hosts:
    server-01:
      ansible_host: 51.250.13.141
    server-02:
      ansible_host: 51.250.1.166
test:
  hosts:
    server-01:
      ansible_host: 51.250.13.141
    server-02:
      ansible_host: 51.250.1.166
