---
vars:
    ansible_connection: ssh   # подключение по ssh
    ansible_ssh_user: parallels     # пользователь
    ansible_ssh_private_key_file: ~/.ssh/id_rsa.pub # ключ откуда берет
    db_user: admin
    db_password: Passw0rd
    db_name: testdb