### alertmanager.yml настройка оповещения!!!!
# подсунуть этот конфиг в нужную директорию

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'yourmailto@todomain.com'
  from: 'yourmailfrom@fromdomain.com'
  smarthost: 'mailserver:25'
  auth_username: 'user'
  auth_identity: 'user'
  auth_password: 'paS$w0rd'