### КОНФИГ для ОПОВЕЩЕНИЯ!
# Прописать в Rules prometheus.yml название конфига netology.yaml

groups:
- name: netology-test
  rules:
  - alert: InstanceDown
    expr: up == 0 # Если лежит
    for: 1m # 1 минуту и более
    labels:
      severity: critical # Критический статус
    annotations: # Описание
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been 
down for more than 1 minute.'
      summary: Instance {{ $labels.instance }} down

