---
- name: Check & Gathering Facts
  hosts: prod
  tasks:
    - name: Enable EPEL Repository on CentOS 8
      become: yes
      dnf:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'
    - name: Enable EPEL Repository on CentOS 7
      become: yes
      yum:
        name: epel-release
        state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '7'
    - name: Update package Centos
      become: yes
      yum:
        name=*
        state=latest
      tags:
        - epel
        - package
    - name: Install HTTPD
      become: yes
      yum:
        name:
          - httpd
          - vim
          - curl
        state: latest
      tags:
        - httpd
        - vim
        - curl
    - name: Start HTTPD
      become: yes
      ansible.builtin.service:
        name: httpd
        state: started
      tags:
        - service 
    - name: Create index.html using Jinja2
      become: yes
      template:
        src: index.j2
        dest: /var/www/html/index.html
      tags:
        - j2

