---
- name: Check & Gathering
  hosts: prod
  tasks:
    - name: Download Promethtus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
    - name: Unarchive Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes