---
- name: Check & Gathering Facts
  hosts: prod
  tasks:
    - name: Download Promethtus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
    - name: Unarchive Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
- name: Create
  hosts: prod
  tasks:
    - name: Create Prometheus Directories
      become: yes
      ansible.builtin.file:
       state: directory
       path: /etc/prometheus
    - name: Change file ownership, group and permissions
      become: yes
      ansible.builtin.file:
       state: directory
       path: /var/lib/prometheus
       owner: prome
       group: prome
       mode: '0644'
- name:
  hosts: prod
  tasks:
    - name: Prometheus User
      become: yes
      ansible.builtin.user:
       name: prome
       comment: prometheus
    - name: Node_exporter user
      become: yes
      ansible.builtin.user:
       name: node_exporter
       comment: node_exporter
- name: Copy directory & file
  hosts: prod
  tasks:
    - name: Copy-1
      become: yes
      ansible.builtin.copy:
       src: prometheus.yml
       dest: /etc/prometheus/prometheus.yml
       owner: prome
       group: prome
       mode: '0644'
    - name: Copy-2
      become: yes
      ansible.builtin.copy:
       src: /tmp/prometheus-2.30.3.linux-amd64/consoles
       dest: /etc/prometheus      
       owner: prome
       group: prome
       mode: '0644'
       remote_src: yes
    - name: Copy-3
      become: yes
      ansible.builtin.copy:
       src: /tmp/prometheus-2.30.3.linux-amd64/console_libraries
       dest: /etc/prometheus      
       owner: prome
       group: prome
       mode: '0644'
       remote_src: yes
    - name: Copy-4
      become: yes
      ansible.builtin.copy:
       src: /tmp/prometheus-2.30.3.linux-amd64/promtool
       dest: /usr/local/bin/     
       owner: prome
       group: prome
       mode: '0644'
       remote_src: yes
    - name: Copy-5
      become: yes
      ansible.builtin.copy:
       src: /tmp/prometheus-2.30.3.linux-amd64/prometheus
       dest: /usr/local/bin/
       owner: prome
       group: prome
       mode: '0644'
       remote_src: yes
    - name: Copy-6
      become: yes
      ansible.builtin.copy:
       src: prometheus.service
       dest: /etc/systemd/system/
    - name: Copy-7
      become: yes
      ansible.builtin.copy:
       src: node_exporter.service
       dest: /etc/systemd/system/   
- name: Start Service
  hosts: prod
  tasks:
    - name: prometheus serives start
      become: yes
      ansible.builtin.service:
        name: prometheus
        state: started
        enabled: yes

       
