---
- name: Check & Gathering Facts
  hosts: prod
  tasks:
    - name: Download Promethtus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
    - name: Unarchive Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
- name:
  hosts: prod
  tasks:
    - name: Create Prometheus Directories
      become: yes
      ansible.builtin.file:
       state: directory
       path: /etc/prometheus
    - name: Change file ownership, group and permissions
      become: yes
      ansible.builtin.file:
       state: directory
       path: /var/lib/prometheus
     #  owner: foo
     #  group: foo
     #  mode: '0644'
- name:
  hosts: prod
  tasks:
    - name: Prometheus User
      become: yes
      ansible.builtin.user:
       name: prome
       comment: prometheus
    - name: Node_exporter user
      become: yes
      ansible.builtin.user:
       name: node_exporter
       comment: node_exporter