{
 "title": "Статус сервисов",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Статусы баз данных Postgresql",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(pg_up, \"db_name\", \"$1\", \"job\", \"(.*)-servicedb.*\")",
     "legendFormat": "{{ db_name }}"
    }
   ]
  },
  {
   "title": "Статусы систем",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{target!~\".+api\"}",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  {
   "title": "Статусы бэк сервисов",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{target=~\".+api\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Статус БД MongoDB",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(mongodb_mongod_replset_member_health, \"db_name\", \"$1\", \"name\", \"(.*).mongodb4.*\")",
     "legendFormat": "{{ db_name }}"
    }
   ]
  }
 ]
}