---
all:
 hosts:
    cent8:
      ansible_host: 51.250.30.121
    cent7:
      ansible_host: 10.129.0.20
    ubuntu:
      ansible_host: 51.250.31.139
prod:
  hosts:
    cent8:
      ansible_host: 51.250.30.121
    cent7:
      ansible_host: 10.129.0.20
    ubuntu:
      ansible_host: 51.250.31.139
test:
  hosts:
    cent8:
      ansible_host: 51.250.30.121
    cent7:
      ansible_host: 10.129.0.20
    ubuntu:
      ansible_host: 51.250.31.139